# Generated by Django 4.1.3 on 2022-12-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('http_method', models.CharField(choices=[('POST', 'post'), ('GET', 'get'), ('PUT', 'put'), ('DELETE', 'delete')], max_length=10, verbose_name='Methode')),
                ('url_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authention.permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nom', models.CharField(max_length=300)),
                ('prenom', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='authention.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
