# Generated by Django 4.1.3 on 2022-12-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authention', '0004_remove_role_permission_role_permission'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
