# Generated by Django 4.1.3 on 2022-12-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authention', '0007_alter_permission_http_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(blank=True, to='authention.permission'),
        ),
    ]
