# Generated by Django 4.1.3 on 2022-12-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authention', '0008_alter_role_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uid',
        ),
    ]
